---
# tasks file for bootstrap

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: wait for port to be available
  ansible.builtin.wait_for:
    port: "{{ ansible_port | default('22') }}"
    timeout: "{{ bootstrap_timeout }}"
  when:
    - ansible_connection is defined
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
    - bootstrap_wait_for_host | bool

- name: prepare system
  block:
    - name: test connection
      ansible.builtin.wait_for_connection:
        timeout: "{{ bootstrap_timeout }}"
      register: bootstrap_connect
      changed_when: no
  rescue:
    - name: gather bootstrap facts
      ansible.builtin.include_tasks:
        file: gather_facts.yml

    - name: install bootstrap packages (raw)
      ansible.builtin.raw: "{{ bootstrap_install.raw }}"
      register: bootstrap_install_packages
      changed_when:
        - (bootstrap_install.stdout_regex in bootstrap_install_packages.stdout and
           bootstrap_os_family in [ "Alpine", "Archlinux", "Gentoo" ]) or
          (bootstrap_install.stdout_regex not in bootstrap_install_packages.stdout and
           bootstrap_os_family in [ "Debian", "RedHat", "Rocky", "Suse" ])

- name: ensure system is prepared
  block:
    - name: gather ansible facts
      ansible.builtin.setup:

    - name: update package cache and upgrade OS with dist (apt/Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: install bootstrap packages (package)
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ bootstrap_facts_packages.split() }}"

- name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow

- name: Uncomment the locale in /etc/locale.gen
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: "^# {{ item }}$"
    line: "{{ item }}"
    state: present
  with_items:
    - "en_US.UTF-8 UTF-8"
    - "ru_RU.UTF-8 UTF-8"

- name: Ensure a locale exists
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - "en_US.UTF-8"
    - "ru_RU.UTF-8"

- name: Update LC_TIME
  ansible.builtin.command:
    cmd: update-locale LANG=en_US.UTF-8 LC_TIME="ru_RU.UTF-8"

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname + '.local' }}"
